# Generated by Django 2.1.5 on 2020-01-26 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bullycomments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_data', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('source', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bullycomments',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.Profile'),
        ),
    ]
